class ChoferModel {
  String firstName;
  String lastName;
  String choferNationalId;

  ChoferModel({
    required this.firstName,
    required this.lastName,
    required this.choferNationalId,
  });

  Map<String, dynamic> toMap() {
    return {
      'firstName': firstName,
      'lastName': lastName,
      'choferNationalId': choferNationalId,
    };
  }
}

List<ChoferModel> choferList = [
ChoferModel(firstName: "ALBERTO", lastName: "MENDEZ CRUZ", choferNationalId: "109710565"),
ChoferModel(firstName: "ALBERT", lastName: "QUESADA CAMBRONERO", choferNationalId: "109630317"),
ChoferModel(firstName: "AXEL", lastName: "KIECHLE NARVAES", choferNationalId: "5427424"),
ChoferModel(firstName: "BYRON", lastName: "RODRIGUEZ ROJAS", choferNationalId: "206640962"),
ChoferModel(firstName: "DANILO", lastName: "LAZO BARRANTES", choferNationalId: "603210117"),
ChoferModel(firstName: "DIEGO", lastName: "ULLOA BRENES", choferNationalId: "112930299"),
ChoferModel(firstName: "DYLAN", lastName: "BARRANTES PORRAS", choferNationalId: "604540183"),
ChoferModel(firstName: "DOUGLAS", lastName: "CASTRO VILLALOBOS", choferNationalId: "1014880657"),
ChoferModel(firstName: "EDDY", lastName: "SEGURA", choferNationalId: "603080496"),
ChoferModel(firstName: "EDGAR", lastName: "ZUÑIGA DIAZ", choferNationalId: "204850414"),
ChoferModel(firstName: "EDUARDO", lastName: "ARGUEDAS MADRIGAL", choferNationalId: "603600300"),
ChoferModel(firstName: "EVANGELISTA", lastName: "QUITOS SIRIAS", choferNationalId: "503650016"),
ChoferModel(firstName: "LUIS FERNANDO", lastName: "INCES MONGE", choferNationalId: "304140964"),
ChoferModel(firstName: "FREDDY", lastName: "MIRANDA QUIROS", choferNationalId: "2646710"),
ChoferModel(firstName: "GILBERTO", lastName: "ALFARO FLORES", choferNationalId: "11186893"),
ChoferModel(firstName: "GILBERTO", lastName: "BARRANTES", choferNationalId: "502750575"),
ChoferModel(firstName: "HELDER", lastName: "LOPEZ PORRAS", choferNationalId: "108060193"),
ChoferModel(firstName: "JONATHAN", lastName: "ARGUEDAS MENDEZ", choferNationalId: "602940882"),
ChoferModel(firstName: "JORDY", lastName: "BARRANTES", choferNationalId: "604390729"),
ChoferModel(firstName: "JOSE DANIEL", lastName: "SEGURA BARAHONA", choferNationalId: "603510190"),
ChoferModel(firstName: "JUNIOR", lastName: "CARVAJAL NUÑEZ", choferNationalId: "207300707"),
ChoferModel(firstName: "KEYLOR", lastName: "LOPEZ ALPIZAR", choferNationalId: "113910858"),
ChoferModel(firstName: "LEONARDO", lastName: "ALVARADO MASIS", choferNationalId: "117140044"),
ChoferModel(firstName: "LUIS", lastName: "MONGE PARRA", choferNationalId: "106690875"),
ChoferModel(firstName: "LUIS ALEXANDER", lastName: "SANCHEZ ALVAREZ", choferNationalId: "6203537"),
ChoferModel(firstName: "MANRIQUE", lastName: "CASTRILLO CHAVEZ", choferNationalId: "901030544"),
ChoferModel(firstName: "ORLANDO", lastName: "VILLEGAS RODRIGUEZ", choferNationalId: "6294850"),
ChoferModel(firstName: "OSCAR", lastName: "CASTRO VILLALOBOS", choferNationalId: "2411960"),
ChoferModel(firstName: "RANDALL ANDREY", lastName: "HERRERA MORA", choferNationalId: "118360119"),
ChoferModel(firstName: "RANDALL MAURICIO", lastName: "MORA MESEN", choferNationalId: "603280219"),
ChoferModel(firstName: "RICARDO", lastName: "ALVARADO MORA", choferNationalId: "104010362"),
ChoferModel(firstName: "ROBERTO", lastName: "ARGUEDAS SOLORZANO", choferNationalId: "601780639"),
ChoferModel(firstName: "ROBERTH", lastName: "CASTRO ZUÑIGA", choferNationalId: "9069757"),
ChoferModel(firstName: "ROBERTO", lastName: "VANEGAS MENDOZA", choferNationalId: "504520309"),
ChoferModel(firstName: "ROGER", lastName: "BOLAÑOS CHAVEZ", choferNationalId: "111630353"),
ChoferModel(firstName: "RONALD", lastName: "MENDEZ MIRANDA", choferNationalId: "603070173"),
ChoferModel(firstName: "RONALD", lastName: "VILLALOBOS FERNANDEZ", choferNationalId: "602230868"),
ChoferModel(firstName: "ROY", lastName: "FERNANDEZ TORRES", choferNationalId: "2689993"),
ChoferModel(firstName: "OSCAR ALEXANDER", lastName: "CONEJO FALLAS", choferNationalId: "10070612"),
ChoferModel(firstName: "CARLOS", lastName: "VARGAS ALPIZAR", choferNationalId: "2337780"),
ChoferModel(firstName: "HAROLD", lastName: "LOPEZ JIMENEZ", choferNationalId: "5323939"),
ChoferModel(firstName: "YEUDI", lastName: "VILLEGAS ROJAS", choferNationalId: "5318243"),
ChoferModel(firstName: "BENEDICTO", lastName: "PANIAGUA CALDERON", choferNationalId: "2353063"),
ChoferModel(firstName: "YAMIL", lastName: "GONZALEZ CAMPOS", choferNationalId: "2607892"),
ChoferModel(firstName: "ROLANDO", lastName: "QUESADA VARGAS", choferNationalId: "2411732"),
ChoferModel(firstName: "EMILIANO", lastName: "QUESADA PERAZA", choferNationalId: "2743899"),
ChoferModel(firstName: "EUGENIO", lastName: "CARRILLO SIBAJA", choferNationalId: "5324021"),
ChoferModel(firstName: "RODOLFO", lastName: "VASQUEZ VASQUEZ", choferNationalId: "2659209"),
ChoferModel(firstName: "CESAR", lastName: "DIAZ ALFARO", choferNationalId: "2509049"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "ZUÑIGA BARBOZA", choferNationalId: "2359903"),
ChoferModel(firstName: "PABLO", lastName: "GONZALEZ CAMPOS", choferNationalId: "2758834"),
ChoferModel(firstName: "LUIS", lastName: "QUESADA VILLALOBOS", choferNationalId: "2410405"),
ChoferModel(firstName: "EDGARDO", lastName: "CHAVARRIA CHAVARRIA", choferNationalId: "5189600"),
ChoferModel(firstName: "OCTAVIO", lastName: "BOLAÑOS ALPIZAR", choferNationalId: "2397042"),
ChoferModel(firstName: "DINIER", lastName: "ALVARADO HERRERA", choferNationalId: "2625432"),
ChoferModel(firstName: "LUIS", lastName: "ARCE ALFARO", choferNationalId: "2560607"),
ChoferModel(firstName: "MARVIN", lastName: "ROJAS AGUERO", choferNationalId: "2679896"),
ChoferModel(firstName: "OLGER", lastName: "PEREZ MURILLO", choferNationalId: "110120857"),
ChoferModel(firstName: "VIRGILIO", lastName: "ESPINOZA CASTRO", choferNationalId: "2359679"),
ChoferModel(firstName: "ROLANDO", lastName: "RODRIGUEZ MONTOYA", choferNationalId: "5220533"),
ChoferModel(firstName: "ORLANDO", lastName: "UMAÑA PORRAS", choferNationalId: "5297984"),
ChoferModel(firstName: "DANIEL", lastName: "SABORIO SALAS", choferNationalId: "114260863"),
ChoferModel(firstName: "JUAN", lastName: "C ZELEDON GONZALEZ", choferNationalId: "2578865"),
ChoferModel(firstName: "CARLOS", lastName: "MORA MIRANDA", choferNationalId: "2474840"),
ChoferModel(firstName: "ISRAEL", lastName: "ARRONES OCON", choferNationalId: "1654224"),
ChoferModel(firstName: "JEFFRY", lastName: "VILLALOBOS GUERRERO", choferNationalId: "2578074"),
ChoferModel(firstName: "HARLAN", lastName: "CESPEDES BARRANTES", choferNationalId: "2667337"),
ChoferModel(firstName: "CRISTOFER", lastName: "QUESADA SALAZAR", choferNationalId: "2800157"),
ChoferModel(firstName: "KEYLOR", lastName: "CRUZ PORRAS", choferNationalId: "2515398"),
ChoferModel(firstName: "JESUS", lastName: "HERRERA QUESADA", choferNationalId: "115110744"),
ChoferModel(firstName: "JEISON BOSCO", lastName: "HERNANDEZ MONTERO", choferNationalId: "603130421"),
ChoferModel(firstName: "ANDREY", lastName: "CERDAS ALVAREZ", choferNationalId: "2584099"),
ChoferModel(firstName: "JOAQUIN", lastName: "HERRERA ARAYA", choferNationalId: "2349096"),
ChoferModel(firstName: "JENARO", lastName: "CHACON ARIAS", choferNationalId: "2388328"),
ChoferModel(firstName: "JOSE PABLO", lastName: "LOPEZ CUBERO", choferNationalId: "2114440948"),
ChoferModel(firstName: "ORLANDO", lastName: "CUBERO BADILLA", choferNationalId: "1969344"),
ChoferModel(firstName: "ELIBER", lastName: "MIRANDA RODRIGUEZ", choferNationalId: "2458712"),
ChoferModel(firstName: "ALONSO", lastName: "MARTINEZ GONZALEZ", choferNationalId: "1980374"),
ChoferModel(firstName: "YEIFRIN", lastName: "ALVARADO HERRERA", choferNationalId: "2588331"),
ChoferModel(firstName: "CARLOS", lastName: "BARRANTES CASTREJON", choferNationalId: "2567026"),
ChoferModel(firstName: "KENDALL", lastName: "MUÑOZ MADRIGAL", choferNationalId: "2572248"),
ChoferModel(firstName: "GEOVANNY", lastName: "VILLEGAS RODRIGUEZ", choferNationalId: "6318484"),
ChoferModel(firstName: "ELIANDER", lastName: "CORDOBA ELIZONDO", choferNationalId: "2420310"),
ChoferModel(firstName: "EDDY", lastName: "HERRERA JIMENEZ", choferNationalId: "2455273"),
ChoferModel(firstName: "JOSE", lastName: "DURAN VASQUEZ", choferNationalId: "2740439"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "CHAVEZ NUÑEZ", choferNationalId: "1949710"),
ChoferModel(firstName: "GUIDO", lastName: "LIZANO ARGUEDAS", choferNationalId: "9043411"),
ChoferModel(firstName: "MANRIQUE", lastName: "PEREZ FALLAS", choferNationalId: "1910458"),
ChoferModel(firstName: "JUAN LUIS", lastName: "ELIZONDO MEJIAS", choferNationalId: "2322197"),
ChoferModel(firstName: "ARNALDO", lastName: "DURAN VASQUEZ", choferNationalId: "2784660"),
ChoferModel(firstName: "MIGUEL", lastName: "PEREZ HERRERA", choferNationalId: "2307385"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "VIQUEZ SANCHEZ", choferNationalId: "6262744"),
ChoferModel(firstName: "HEINER", lastName: "QUESADA GONZALES", choferNationalId: "2580483"),
ChoferModel(firstName: "JUAN", lastName: "VIQUEZ RODRIGUEZ", choferNationalId: "112190360"),
ChoferModel(firstName: "JUAN", lastName: "VIQUEZ CHAVEZ", choferNationalId: "2391473"),
ChoferModel(firstName: "DIEGO", lastName: "SIBAJA SANCHEZ", choferNationalId: "1104421"),
ChoferModel(firstName: "HERNAN", lastName: "QUESADA GONZALEZ", choferNationalId: "2837510"),
ChoferModel(firstName: "JASON", lastName: "DAVILA MARTINEZ", choferNationalId: "5346934"),
ChoferModel(firstName: "ALEX", lastName: "ATENCIO CASTRILLO", choferNationalId: "6217048"),
ChoferModel(firstName: "CARLOS", lastName: "ALPIZAR BOLAÑOS", choferNationalId: "2737651"),
ChoferModel(firstName: "JOSE CLAUDIO", lastName: "CUBERO RAMIREZ", choferNationalId: "2722964"),
ChoferModel(firstName: "GREIVIN", lastName: "MENDEZ PIZARRO", choferNationalId: "5341100"),
ChoferModel(firstName: "MARCOS", lastName: "SOTO ALVAREZ", choferNationalId: "6365099"),
ChoferModel(firstName: "RAFAEL", lastName: "MORALES MONTOYA", choferNationalId: "1785636"),
ChoferModel(firstName: "KEYLOR", lastName: "QUESADA VARGAS", choferNationalId: "2566635"),
ChoferModel(firstName: "ANDRES", lastName: "CHAVEZ HERRA", choferNationalId: "114280020"),
ChoferModel(firstName: "CARLOS", lastName: "BARRANTES SIBAJA", choferNationalId: "4136919"),
ChoferModel(firstName: "LUIS ENRIQUE", lastName: "MOLINA CASTILLO", choferNationalId: "6284827"),
ChoferModel(firstName: "JOSE", lastName: "GONZALEZ PORRAS", choferNationalId: "6407647"),
ChoferModel(firstName: "WILSON", lastName: "SOLIS ALPIZAR", choferNationalId: "2637570"),
ChoferModel(firstName: "EFRAIN", lastName: "VILLALOBOS RAMIREZ", choferNationalId: "5343561"),
ChoferModel(firstName: "JOSE", lastName: "CASTRO SOTO", choferNationalId: "117890726"),
ChoferModel(firstName: "NORMAN", lastName: "SEGURA SOTO", choferNationalId: "2487772"),
ChoferModel(firstName: "ARMANDO", lastName: "ROJAS MOLINA", choferNationalId: "7110649"),
ChoferModel(firstName: "RANDALL", lastName: "MIRANDA LARA", choferNationalId: "2498780"),
ChoferModel(firstName: "ADRIÁN", lastName: "ALVARADO GRANADOS", choferNationalId: "112660107"),
ChoferModel(firstName: "CRISTIAN", lastName: "ESPINOZA DELGADO", choferNationalId: "110150205"),
ChoferModel(firstName: "RONALD", lastName: "HERRERA MORALES", choferNationalId: "2751710"),
ChoferModel(firstName: "MIGUEL", lastName: "CASTRO ZUÑIGA", choferNationalId: "1692873"),
ChoferModel(firstName: "CRISTIAN", lastName: "SALAZAR CORRALES", choferNationalId: "2560538"),
ChoferModel(firstName: "ISAAC", lastName: "QUESADA ESPINOZA", choferNationalId: "2604430"),
ChoferModel(firstName: "JOEL", lastName: "QUESADA ESPINOZA", choferNationalId: "2502382"),
ChoferModel(firstName: "FRANCISCO", lastName: "CRUZ LOPEZ", choferNationalId: "8091748"),
ChoferModel(firstName: "GREIVIN", lastName: "PEREZ FALLAS", choferNationalId: "2640577"),
ChoferModel(firstName: "MARCOS", lastName: "RUIZ AVILA", choferNationalId: "2534872"),
ChoferModel(firstName: "ROY", lastName: "PEREZ FALLAS", choferNationalId: "2545863"),
ChoferModel(firstName: "OLMAN", lastName: "SALAZAR MURILLO", choferNationalId: "2467268"),
ChoferModel(firstName: "ALLAN", lastName: "GOMEZ GOMEZ", choferNationalId: "2544410"),
ChoferModel(firstName: "ROY", lastName: "RIVERA HERRERA", choferNationalId: "2660439"),
ChoferModel(firstName: "DIEGO", lastName: "PORRAS ARIAS", choferNationalId: "6416352"),
ChoferModel(firstName: "JOSUE", lastName: "PORRAS ARIAS", choferNationalId: "6401406"),
ChoferModel(firstName: "ESTEBAN", lastName: "CAMPOS CABEZAS", choferNationalId: "2597413"),
ChoferModel(firstName: "ALEXANDER", lastName: "SOLIS CORRALES", choferNationalId: "6413811"),
ChoferModel(firstName: "FRANKLIN", lastName: "RAMIREZ LEON", choferNationalId: "110270053"),
ChoferModel(firstName: "JONATHAN", lastName: "ROJAS ESPINOZA", choferNationalId: "2573131"),
ChoferModel(firstName: "ALEJANDRO", lastName: "VALVERDE GARCIA", choferNationalId: "2686250"),
ChoferModel(firstName: "ANDRES", lastName: "RODRIGUEZ ARAYA", choferNationalId: "6397826"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "ROJAS ESPINOZA", choferNationalId: "2637298"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "ROJAS ALFARO", choferNationalId: "2402449"),
ChoferModel(firstName: "ANDY", lastName: "GORGONA CRUZ", choferNationalId: "6368344"),
ChoferModel(firstName: "JESUS", lastName: "PEREZ GONZALEZ", choferNationalId: "2715257"),
ChoferModel(firstName: "DIEGO", lastName: "MOLINA DELGADO", choferNationalId: "2628754"),
ChoferModel(firstName: "JUAN JOSE", lastName: "SOLIS SOLIS", choferNationalId: "1779381"),
ChoferModel(firstName: "ULISES", lastName: "QUESADA BUSTOS", choferNationalId: "6340144"),
ChoferModel(firstName: "JOSE", lastName: "GUTIERREZ RODRIGUEZ", choferNationalId: "115240774"),
ChoferModel(firstName: "CLAUDIO", lastName: "ALVARADO AGUIRRE", choferNationalId: "6327269"),
ChoferModel(firstName: "HELDER", lastName: "LOPEZ PORRAS", choferNationalId: "1806193"),
ChoferModel(firstName: "WAGNER", lastName: "ALFARO HERRERA", choferNationalId: "1949390"),
ChoferModel(firstName: "JESUS", lastName: "ESPINOZA CRUZ", choferNationalId: "113850605"),
ChoferModel(firstName: "JERRY", lastName: "ORTEGA SEGURA", choferNationalId: "6330368"),
ChoferModel(firstName: "PABLO", lastName: "CORDERO CORTEZ", choferNationalId: "6366275"),
ChoferModel(firstName: "GERARDO", lastName: "SOTO VELEZ", choferNationalId: "113770562"),
ChoferModel(firstName: "YONSE", lastName: "MORA ALPIZAR", choferNationalId: "2495252"),
ChoferModel(firstName: "MELVIN", lastName: "SANCHEZ MATA", choferNationalId: "2612707"),
ChoferModel(firstName: "GEOVANNY", lastName: "RAMIREZ VELEZ", choferNationalId: "6166053"),
ChoferModel(firstName: "JEFFRY", lastName: "ALVAREZ MORERA", choferNationalId: "6419231"),
ChoferModel(firstName: "JHONNY", lastName: "MUÑOZ ARROYO", choferNationalId: "2723252"),
ChoferModel(firstName: "RAUL", lastName: "AGUILAR CARVAJAL", choferNationalId: "4122664"),
ChoferModel(firstName: "WILLIAM", lastName: "PORRAS GOMEZ", choferNationalId: "5339571"),
ChoferModel(firstName: "FRANCISCO", lastName: "DURÁN VARELA", choferNationalId: "2425560"),
ChoferModel(firstName: "HELMAN", lastName: "GUERRERO VASQUEZ", choferNationalId: "1538971"),
ChoferModel(firstName: "HELMAN", lastName: "GUERRERO TRAÑA", choferNationalId: "6452793"),
ChoferModel(firstName: "ANDREY", lastName: "MUÑOZ SOSA", choferNationalId: "6324246"),
ChoferModel(firstName: "ANDREY", lastName: "JIMENEZ ESPINOZA", choferNationalId: "6367658"),
ChoferModel(firstName: "OLGER", lastName: "PALMA GUERRERO", choferNationalId: "6159171"),
ChoferModel(firstName: "MARTIN", lastName: "LIZANO MOYA", choferNationalId: "1791680"),
ChoferModel(firstName: "OSCAR", lastName: "GONZALEZ SUAREZ", choferNationalId: "6256909"),
ChoferModel(firstName: "MAX", lastName: "RAMIREZ GONZALEZ", choferNationalId: "2548156"),
ChoferModel(firstName: "EMANUEL", lastName: "SOLORZANO VENEGAS", choferNationalId: "113870812"),
ChoferModel(firstName: "ORLANDO", lastName: "BRIZUELA ROJAS", choferNationalId: "6317859"),
ChoferModel(firstName: "CARLOS", lastName: "LORIA RODRIGUEZ", choferNationalId: "9092952"),
ChoferModel(firstName: "EMILIO", lastName: "LOPEZ PANIAGUA", choferNationalId: "2518550"),
ChoferModel(firstName: "CARLOS", lastName: "BARRIENTOS ALVARADO", choferNationalId: "2544818"),
ChoferModel(firstName: "KENNETH", lastName: "ALFARO SANDOVAL", choferNationalId: "6354891"),
ChoferModel(firstName: "GILBERTO", lastName: "ESPINOZA RIOS", choferNationalId: "5347975"),
ChoferModel(firstName: "JUSTIN", lastName: "LEON UGALDE", choferNationalId: "6458214"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "PORRAS RODRIGUEZ", choferNationalId: "206310692"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "PORRAS RODRIGUEZ", choferNationalId: "113170799"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "PORRAS RODRIGUEZ", choferNationalId: "118260758"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "PORRAS RODRIGUEZ", choferNationalId: "208210541"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "PORRAS RODRIGUEZ", choferNationalId: "603840857"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "107380277"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "303540269"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "111550054"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "701790392"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "603670263"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "RODRIGUEZ MORA", choferNationalId: "116820450"),
ChoferModel(firstName: "GERARDO", lastName: "ALPIZAR SOLIS", choferNationalId: "2533085"),
ChoferModel(firstName: "JAIRO", lastName: "SOLIS MORA", choferNationalId: "6304616"),
ChoferModel(firstName: "MAURICIO", lastName: "MENDEZ DÍAZ", choferNationalId: "6296140"),
ChoferModel(firstName: "FERNANDO", lastName: "DELGADO MENDEZ", choferNationalId: "1577852"),
ChoferModel(firstName: "LUIS FERNANDO", lastName: "DELGADO ARIAS", choferNationalId: "112850017"),
ChoferModel(firstName: "FRANCIS", lastName: "JIMENEZ ZUÑIGA", choferNationalId: "1868316"),
ChoferModel(firstName: "LUIS", lastName: "SUAREZ HERRERA", choferNationalId: "111790686"),
ChoferModel(firstName: "ERICK", lastName: "TREJOS BONILLA", choferNationalId: "6322403"),
ChoferModel(firstName: "VICTOR", lastName: "CHAVEZ RODRIGUEZ", choferNationalId: "9065909"),
ChoferModel(firstName: "ALLAN", lastName: "VILLALOBOS ARCE", choferNationalId: "5312361"),
ChoferModel(firstName: "CRISTIAN", lastName: "OCAMPO CASCANTE", choferNationalId: "6302557"),
ChoferModel(firstName: "JOSE", lastName: "ALFARO VALVERDE", choferNationalId: "2420580"),
ChoferModel(firstName: "ROGER", lastName: "ZAMORA ENRIQUEZ", choferNationalId: "6119519"),
ChoferModel(firstName: "CELIMO", lastName: "JIMENEZ ELIZONDO", choferNationalId: "6169495"),
ChoferModel(firstName: "MAINOR", lastName: "CESPEDES QUESADA", choferNationalId: "2508582"),
ChoferModel(firstName: "MIGUEL MAURICIO", lastName: "CASTRO ZUÑIGA", choferNationalId: "900920910"),
ChoferModel(firstName: "ALVARO", lastName: "BURFORD HIDALGO", choferNationalId: "115460218"),
ChoferModel(firstName: "JOAQUIN", lastName: "RAMIREZ UGALDE", choferNationalId: "2545736"),
ChoferModel(firstName: "HANS", lastName: "ALPIZAR QUESADA", choferNationalId: "2617071"),
ChoferModel(firstName: "PHILLIP", lastName: "RIOS JIMENEZ", choferNationalId: "2789157"),
ChoferModel(firstName: "JOSE A", lastName: "ALVARADO VARGAS", choferNationalId: "9072140"),
ChoferModel(firstName: "JULIO", lastName: "VILLALOBOS VIQUEZ", choferNationalId: "41051272"),
ChoferModel(firstName: "RAUL", lastName: "VEGA HERRERA", choferNationalId: "2340719"),
ChoferModel(firstName: "ALFREDO", lastName: "MURILLO JIMENEZ", choferNationalId: "2395238"),
ChoferModel(firstName: "CARLOS", lastName: "QUESADA MURILLO", choferNationalId: "2308433"),
ChoferModel(firstName: "WILLIAM", lastName: "LEDEZMA MADRIGAL", choferNationalId: "2358312"),
ChoferModel(firstName: "MICHAEL", lastName: "ARIAS CASTRO", choferNationalId: "2575652"),
ChoferModel(firstName: "JUAN PABLO", lastName: "PORRAS PORRAS", choferNationalId: "116800355"),
ChoferModel(firstName: "GABRIEL", lastName: "HERNANDEZ VARGAS", choferNationalId: "2396933"),
ChoferModel(firstName: "RONALD", lastName: "OTAROLA RUEDA", choferNationalId: "2666281"),
ChoferModel(firstName: "JOHAN", lastName: "ALVARADO GOMEZ", choferNationalId: "2729415"),
ChoferModel(firstName: "JOSE", lastName: "VIQUEZ LEON", choferNationalId: "2600032"),
ChoferModel(firstName: "JUAN L", lastName: "GONZALEZ MENDEZ", choferNationalId: "2469651"),
ChoferModel(firstName: "RODRIGO", lastName: "HERRERA ALFARO", choferNationalId: "2403418"),
ChoferModel(firstName: "ERICK", lastName: "CASTRO GONZALEZ", choferNationalId: "2545024"),
ChoferModel(firstName: "JOSE", lastName: "MURILLO ESPINOZA", choferNationalId: "2515764"),
ChoferModel(firstName: "ELESBAN", lastName: "RAMOS VIQUEZ", choferNationalId: "4132775"),
ChoferModel(firstName: "ANDRES", lastName: "LEON RAMIREZ", choferNationalId: "2540437"),
ChoferModel(firstName: "JORGE", lastName: "ALFARO ALFARO", choferNationalId: "2430345"),
ChoferModel(firstName: "ALFREDO", lastName: "MADRIGAL DURAN", choferNationalId: "2690116"),
ChoferModel(firstName: "WILLIAM", lastName: "GONZALEZ MORA", choferNationalId: "6273323"),
ChoferModel(firstName: "JONATHAN", lastName: "ESPINOZA MONGE", choferNationalId: "2623122"),
ChoferModel(firstName: "EDGAR", lastName: "SALGUERO ORTIZ", choferNationalId: "2600604"),
ChoferModel(firstName: "JORGE", lastName: "GARITA CAMBRONERO", choferNationalId: "111760895"),
ChoferModel(firstName: "ARIEL", lastName: "VARGAS CORDOBA", choferNationalId: "116940547"),
ChoferModel(firstName: "LUIS", lastName: "VARGAS CASTRO", choferNationalId: "2345177"),
ChoferModel(firstName: "BENEDICTO", lastName: "CHACON JIMENEZ", choferNationalId: "4123808"),
ChoferModel(firstName: "LINO", lastName: "GONZALEZ PEREZ", choferNationalId: "52344451"),
ChoferModel(firstName: "EDSON", lastName: "VENEGAS MONTERO", choferNationalId: "2575275"),
ChoferModel(firstName: "MICHAEL", lastName: "RODRIGUEZ ARAYA", choferNationalId: "6301322"),
ChoferModel(firstName: "MARCOS", lastName: "SANTAMARÍA RAMIREZ", choferNationalId: "2737284"),
ChoferModel(firstName: "MARCOS", lastName: "SANTAMARÍA SALAZAR", choferNationalId: "2361672"),
ChoferModel(firstName: "CARLOS", lastName: "VARGAS BARTH", choferNationalId: "112220534"),
ChoferModel(firstName: "GUSTAVO", lastName: "ACUNA SANCHO", choferNationalId: "6386990"),
ChoferModel(firstName: "GABRIEL", lastName: "ALPIZAR RODRIGUEZ", choferNationalId: "2410700"),
ChoferModel(firstName: "GLEN", lastName: "MADRIGAL SABORIO", choferNationalId: "1794669"),
ChoferModel(firstName: "ESTEBAN", lastName: "ALFARO RODRIGUEZ", choferNationalId: "2612453"),
ChoferModel(firstName: "JOSE", lastName: "GONZALEZ ALPIZAR", choferNationalId: "2578200"),
ChoferModel(firstName: "JOSE", lastName: "GONZALEZ SANCHEZ", choferNationalId: "111590128"),
ChoferModel(firstName: "MARCOS RONEY", lastName: "MONGE MARTINEZ", choferNationalId: "602750096"),
ChoferModel(firstName: "MARCOS ANTONIO", lastName: "MONGE MARTINEZ", choferNationalId: "207410353"),
ChoferModel(firstName: "MARCOS", lastName: "VEGA VEGA", choferNationalId: "6364873"),
ChoferModel(firstName: "OMAR", lastName: "CHAVEZ HERRERA", choferNationalId: "2337465"),
ChoferModel(firstName: "AMADEO", lastName: "CHAVEZ HERRERA", choferNationalId: "2286386"),
ChoferModel(firstName: "EDUARDO", lastName: "RAMIREZ QUESADA", choferNationalId: "2622333"),
ChoferModel(firstName: "FRANCISCO", lastName: "SANCHEZ ARGUEDAS", choferNationalId: "2383911"),
ChoferModel(firstName: "JUAN", lastName: "LEPIZ SALAZAR", choferNationalId: "7110939"),
ChoferModel(firstName: "OCTAVIO", lastName: "CHAVEZ SOLIS", choferNationalId: "2794418"),
ChoferModel(firstName: "ALEJANDRO", lastName: "PERAZA SANCHEZ", choferNationalId: "2744418"),
ChoferModel(firstName: "SERGIO A", lastName: "NARANJO MENDOZA", choferNationalId: "206110233"),
ChoferModel(firstName: "JOSE A", lastName: "GONZALES ARRIETA", choferNationalId: "206660790"),
ChoferModel(firstName: "GREIVIN", lastName: "BENAVIDES ULLOA", choferNationalId: "113210814"),
ChoferModel(firstName: "JOSE DAVID", lastName: "NUÑEZ CAMPOS", choferNationalId: "205880454"),
ChoferModel(firstName: "CRISTIAN", lastName: "LOPEZ ESPINOZA", choferNationalId: "2583499"),
ChoferModel(firstName: "ROGER", lastName: "MADRIGAL MADRIGAL", choferNationalId: "2547703"),
ChoferModel(firstName: "LUIS ADRIEL", lastName: "SOTO OLMOS", choferNationalId: "206090149"),
ChoferModel(firstName: "ANDREY", lastName: "RODRIGUEZ MORA", choferNationalId: "112870284"),
ChoferModel(firstName: "ROBERT ADRIAN", lastName: "MONGE SOLANO", choferNationalId: "604040102"),
ChoferModel(firstName: "MAURICIO", lastName: "CORRALES MUÑOZ", choferNationalId: "1786126"),
ChoferModel(firstName: "ANDRES", lastName: "VEGA FERNANDEZ", choferNationalId: "3381218"),
ChoferModel(firstName: "DENIS", lastName: "CERDAS BERROCAL", choferNationalId: "110300816"),
ChoferModel(firstName: "MARCOS", lastName: "CERVANTES VARGAS", choferNationalId: "3399131"),
ChoferModel(firstName: "JONATHAN", lastName: "VILLALOBOS VALVERDE", choferNationalId: "2603470"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "DELGADO GALLARDO", choferNationalId: "117510905"),
ChoferModel(firstName: "SERGIO", lastName: "GONZALES CAMPOS", choferNationalId: "2706895"),
ChoferModel(firstName: "GUSTAVO", lastName: "CAMPOS RODRIGUEZ", choferNationalId: "2542865"),
ChoferModel(firstName: "JOSE BRICEÑO", lastName: "ATENCIO", choferNationalId: "603460739"),
ChoferModel(firstName: "BRAYAN", lastName: "MENDEZ LOPEZ", choferNationalId: "2612053"),
ChoferModel(firstName: "MOISES", lastName: "ARAYA MURILLO", choferNationalId: "2546598"),
ChoferModel(firstName: "CARLOS", lastName: "VARGAS RODRIGUEZ", choferNationalId: "6339334"),
ChoferModel(firstName: "JOSE A", lastName: "ALVARADO VARGAS", choferNationalId: "900720140"),
ChoferModel(firstName: "JUAN", lastName: "PEREZ BELLIDO", choferNationalId: "503750753"),
ChoferModel(firstName: "MANUEL", lastName: "MURILLO SIRIAS", choferNationalId: "6270947"),
ChoferModel(firstName: "ALONSO", lastName: "MARTINEZ GONZALES", choferNationalId: "109800374"),
ChoferModel(firstName: "GUILLERMO", lastName: "MARTINEZ GONZALEZ", choferNationalId: "111630018"),
ChoferModel(firstName: "MARIO", lastName: "VARGAS ARGUELLO", choferNationalId: "2350318"),
ChoferModel(firstName: "STEVEN", lastName: "CUBILLO CARRILLO", choferNationalId: "6304964"),
ChoferModel(firstName: "OSCAR", lastName: "ZUÑIGA SOLANO", choferNationalId: "4109657"),
ChoferModel(firstName: "JOANY", lastName: "ARGUEDAS ROJAS", choferNationalId: "2463018"),
ChoferModel(firstName: "DANIEL", lastName: "CORTEZ GONZALES", choferNationalId: "5259175"),
ChoferModel(firstName: "ORLANDO", lastName: "MEJIA FERNANDEZ", choferNationalId: "6289074"),
ChoferModel(firstName: "STEVEN", lastName: "CORDERO SOTO", choferNationalId: "112810307"),
ChoferModel(firstName: "OSCAR MARIO", lastName: "MORERA LOPEZ", choferNationalId: "2418399"),
ChoferModel(firstName: "CARLOS ANDRE", lastName: "VARELA ULATE", choferNationalId: "117320326"),
ChoferModel(firstName: "CARLOS GERARDO", lastName: "VARELA ULATE", choferNationalId: "402260783"),
ChoferModel(firstName: "CARLOS MANUEL", lastName: "VARELA ULATE", choferNationalId: "204420782"),
ChoferModel(firstName: "RICARDO", lastName: "ROJAS ZAMORA", choferNationalId: "2417083"),
ChoferModel(firstName: "JAFET", lastName: "GONZALES ZELEDON", choferNationalId: "5208690"),
ChoferModel(firstName: "MIGUEL ANGEL", lastName: "CASTRO GUIDO", choferNationalId: "2580882"),
ChoferModel(firstName: "JOSEPH", lastName: "CASTILLO SIMONI", choferNationalId: "2620297"),
ChoferModel(firstName: "GUILLERMO", lastName: "POVEDA WACSON", choferNationalId: "3500185"),
ChoferModel(firstName: "ANDREY", lastName: "CAMPOS ROJAS", choferNationalId: "7172770"),
ChoferModel(firstName: "ISMAEL", lastName: "VARGAS ROJAS", choferNationalId: "113250706"),
ChoferModel(firstName: "RICARDO", lastName: "MAROTO CORELLA", choferNationalId: "1936670"),
ChoferModel(firstName: "ARON", lastName: "MORERA QUESADA", choferNationalId: "2645831"),
ChoferModel(firstName: "MAURICIO", lastName: "NUÑEZ ALVARADO", choferNationalId: "2536193"),
ChoferModel(firstName: "CRISTIAN", lastName: "LOBO ROJAS", choferNationalId: "1925023"),
ChoferModel(firstName: "FRANKLIN", lastName: "ROJAS VILLALTA", choferNationalId: "115670787"),
ChoferModel(firstName: "LORENZO", lastName: "SALAS CONEJO", choferNationalId: "5245662"),
ChoferModel(firstName: "MAINOR", lastName: "BOLAÑOS CORRALES", choferNationalId: "116720650"),
ChoferModel(firstName: "LIZANIAS", lastName: "ESQUIVEL CHAVARRIA", choferNationalId: "2436911"),
ChoferModel(firstName: "MANUEL", lastName: "RODRIGUEZ CERDAS", choferNationalId: "4178323"),
ChoferModel(firstName: "ALBERTO", lastName: "MURILLO JIMENEZ", choferNationalId: "203410665"),
ChoferModel(firstName: "SERGIO", lastName: "GONZALES OVIEDO", choferNationalId: "2441572"),
ChoferModel(firstName: "LEONARDO", lastName: "ARRIETA MONTERO", choferNationalId: "6369699"),
ChoferModel(firstName: "GERARDO", lastName: "GONZALES CAMPOS", choferNationalId: "2638897"),
ChoferModel(firstName: "RICARDO", lastName: "MAROTO VARGAS", choferNationalId: "2271822"),
ChoferModel(firstName: "GEINER", lastName: "CORRALES VARGAS", choferNationalId: "2544671"),
ChoferModel(firstName: "ROY", lastName: "OVIEDO QUESADA", choferNationalId: "2526762"),
ChoferModel(firstName: "LUIS CARLOS", lastName: "CASTRO MEJIA", choferNationalId: "112520340"),
ChoferModel(firstName: "KEREN ESTEBAN", lastName: "LOBO ESTRADA", choferNationalId: "208000601"),
ChoferModel(firstName: "JESUS", lastName: "CHAVEZ MURILLO", choferNationalId: "2619434"),
ChoferModel(firstName: "FELIPE", lastName: "CHAVEZ MURILLO", choferNationalId: "2563202"),
ChoferModel(firstName: "DAVID", lastName: "RODRIGUEZ CAMPOS", choferNationalId: "2560397"),
ChoferModel(firstName: "CARLOS", lastName: "VASQUEZ VILLALOBOS", choferNationalId: "2626147"),
ChoferModel(firstName: "CARLOS", lastName: "BRENES VEGA", choferNationalId: "2343690"),
ChoferModel(firstName: "JOSE J", lastName: "RODRIGUEZ SOLORZANO", choferNationalId: "2538110"),
ChoferModel(firstName: "JOSE", lastName: "HIDALGO BARRIENTOS", choferNationalId: "2456640"),
ChoferModel(firstName: "WALTER", lastName: "RODRIGUEZ MEJIAS", choferNationalId: "2515434"),
ChoferModel(firstName: "CRISTHOFER", lastName: "MENDOZA PRADO", choferNationalId: "6404433"),
ChoferModel(firstName: "JORGE", lastName: "BRENES SANDOVAL", choferNationalId: "5319129"),
ChoferModel(firstName: "JASON", lastName: "VEGA VEGA", choferNationalId: "604090790"),
ChoferModel(firstName: "YUSTIN", lastName: "ARIAS CHAVEZ", choferNationalId: "2781860"),
ChoferModel(firstName: "VICTOR", lastName: "FALLAS GONZALES", choferNationalId: "2557386"),
ChoferModel(firstName: "KEVIN", lastName: "MEJIA ALPIZAR", choferNationalId: "2779856"),
ChoferModel(firstName: "RONALD", lastName: "GONZALES QUESADA", choferNationalId: "2413370"),
ChoferModel(firstName: "DIONISIO", lastName: "SAVEDRA HERNANDEZ", choferNationalId: "1940389"),
ChoferModel(firstName: "DIXON AARON", lastName: "CALDERON CORRALES", choferNationalId: "116420056"),
ChoferModel(firstName: "DIEGO", lastName: "GUTIERREZ ARGUEDAS", choferNationalId: "2707301"),
ChoferModel(firstName: "GUSTAVO", lastName: "PORRAS ALEMAN", choferNationalId: "6350402"),
ChoferModel(firstName: "DARIO", lastName: "PERAZA MONTOYA", choferNationalId: "206090968"),
ChoferModel(firstName: "DAVID", lastName: "RAMIREZ CHAVEZ", choferNationalId: "113960412"),
ChoferModel(firstName: "LEONEL", lastName: "ELIZONDO DIAS", choferNationalId: "6369685"),
ChoferModel(firstName: "BAYRON", lastName: "CUBERO NUÑEZ", choferNationalId: "2707670"),
ChoferModel(firstName: "GERALD", lastName: "MONTERO NUÑEZ", choferNationalId: "6417913"),
ChoferModel(firstName: "MAURICIO", lastName: "MARIN GONZALES", choferNationalId: "114500483"),
ChoferModel(firstName: "MILTON", lastName: "ZUMBADO RIOS", choferNationalId: "110550546"),
ChoferModel(firstName: "JUAN DIEGO", lastName: "SANDI ZUÑIGA", choferNationalId: "114150422"),
ChoferModel(firstName: "LUIS G", lastName: "CHAVARRIA JIMENEZ", choferNationalId: "9107136"),
ChoferModel(firstName: "JAVIER", lastName: "NUÑEZ NUÑEZ", choferNationalId: "2753995"),
ChoferModel(firstName: "ELADIO", lastName: "ZUMBADO SALAS", choferNationalId: "2408155"),
ChoferModel(firstName: "ARIEL", lastName: "GARCIA SOLIS", choferNationalId: "112960888"),
ChoferModel(firstName: "ANTONIO", lastName: "CESPEDEZ SOLIS", choferNationalId: "112520540"),
ChoferModel(firstName: "ALEJANDRO", lastName: "MORA MIRANDA", choferNationalId: "2730237"),
ChoferModel(firstName: "ALBERTO", lastName: "VARGAS CALDERON", choferNationalId: "7660946"),
ChoferModel(firstName: "JOSE MIGUEL", lastName: "SOTO LUNA", choferNationalId: "2340176"),
ChoferModel(firstName: "KEVIN", lastName: "GONZALES MARTINEZ", choferNationalId: "2683484"),
ChoferModel(firstName: "ADRIAN", lastName: "ARCE SANCHEZ", choferNationalId: "4191673"),
ChoferModel(firstName: "DAVID", lastName: "VILLALOBOS PERAZA", choferNationalId: "2651007"),
ChoferModel(firstName: "JOSUE", lastName: "SOTO CAMPOS", choferNationalId: "2797854"),
ChoferModel(firstName: "JORGE", lastName: "HERRERA PEREZ", choferNationalId: "2525960"),
ChoferModel(firstName: "DIEGO ARIAS", lastName: "HERNANDEZ", choferNationalId: "2589231"),
ChoferModel(firstName: "MARCOS IVAN", lastName: "QUESDA MARIN", choferNationalId: "206200282"),
ChoferModel(firstName: "JOCKSEMAN", lastName: "CHACON ARCE", choferNationalId: "6297755"),
ChoferModel(firstName: "DAVID", lastName: "VASQUEZ ALVARADO", choferNationalId: "3471935"),
ChoferModel(firstName: "DELMER", lastName: "GONZALES ALVARADO", choferNationalId: "6377840"),
ChoferModel(firstName: "YOHAN", lastName: "CORTEZ ORDOÑEZ", choferNationalId: "5321355"),
ChoferModel(firstName: "RANDAL", lastName: "MORA MESEN", choferNationalId: "6328219"),
ChoferModel(firstName: "CARLOS", lastName: "MURILLO HERRERA", choferNationalId: "2346186"),
ChoferModel(firstName: "ANTHONY", lastName: "MURILLO NUÑEZ", choferNationalId: "116270813"),
ChoferModel(firstName: "LUIS GUTIERREZ", lastName: "HURTADO", choferNationalId: "6413049"),
ChoferModel(firstName: "JEISON", lastName: "MORA BRENES", choferNationalId: "7182854"),
ChoferModel(firstName: "WILLIAN", lastName: "ARAYA ELIZONDO", choferNationalId: "2692637"),
ChoferModel(firstName: "CESAR", lastName: "ALVAREZ VENEGAS", choferNationalId: "2374901"),
ChoferModel(firstName: "JULIO", lastName: "LEITON SOTO", choferNationalId: "5326689"),
ChoferModel(firstName: "HUGO", lastName: "PEREIRA SEGURA", choferNationalId: "115420179"),
ChoferModel(firstName: "DENIS", lastName: "ARAGON BARRANTES", choferNationalId: "3419156"),
ChoferModel(firstName: "KEYLIN MAURICIO IRIAS", lastName: "AMAYA", choferNationalId: "6322673"),
ChoferModel(firstName: "CARLOS LUIS", lastName: "GARCIA UGALDE", choferNationalId: "204880314"),
ChoferModel(firstName: "GERARDO", lastName: "ALVAREZ RODRIGUEZ", choferNationalId: "2370553"),
ChoferModel(firstName: "EDUARDO", lastName: "CALVO CARMONA", choferNationalId: "1740814"),
ChoferModel(firstName: "ADRIAN", lastName: "RAMIREZ MARIN", choferNationalId: "1904546"),
ChoferModel(firstName: "GREIVIN", lastName: "HERRA ARAYA", choferNationalId: "6300731"),
ChoferModel(firstName: "RAFAEL", lastName: "SOTO LUNA", choferNationalId: "22881083"),
ChoferModel(firstName: "EDDY", lastName: "RODRIGUEZ MORA", choferNationalId: "1795736"),
ChoferModel(firstName: "ERNESTO", lastName: "RODRIGUEZ CRUZ", choferNationalId: "2600120"),
ChoferModel(firstName: "MAICOL", lastName: "ALFARO SEGURA", choferNationalId: "2583085"),
ChoferModel(firstName: "GUSTAVO", lastName: "GUTIERREZ LOPEZ", choferNationalId: "1140000837"),
ChoferModel(firstName: "GERARDO", lastName: "GUERRERO GUERRERO", choferNationalId: "3342071"),
ChoferModel(firstName: "PEDRO", lastName: "SUAREZ ABARCA", choferNationalId: "2632010"),
ChoferModel(firstName: "HENRRY", lastName: "CAMPOS GUTIERREZ", choferNationalId: "6402747"),
ChoferModel(firstName: "LUIS", lastName: "SERRANO VILLEGAS", choferNationalId: "2469855"),
ChoferModel(firstName: "LUIS DIEGO", lastName: "ESPINOZA NUÑEZ", choferNationalId: "2667129"),
ChoferModel(firstName: "FELIPE", lastName: "PEÑA ZUÑIGA", choferNationalId: "3457064"),
ChoferModel(firstName: "MARCO TULIO", lastName: "ARAYA MADRIGAL", choferNationalId: "2528542"),
ChoferModel(firstName: "CARLOS", lastName: "CESPEDEZ QUESADA", choferNationalId: "2419265"),
ChoferModel(firstName: "JUAN LUIS", lastName: "ELIZONDO MEJIA", choferNationalId: "2322195"),
ChoferModel(firstName: "JUAN CARLOS", lastName: "HERRERA SIBAJA", choferNationalId: "6336801"),
ChoferModel(firstName: "JOSE", lastName: "SANCHO ALPIZAR", choferNationalId: "2559446"),
ChoferModel(firstName: "JAVIER", lastName: "CEDEÑO VASQUEZ", choferNationalId: "6252497"),
ChoferModel(firstName: "GEOVANY", lastName: "MIRANDA MESEN", choferNationalId: "26160730"),
ChoferModel(firstName: "WALTER", lastName: "GONZALES JIMENEZ", choferNationalId: "702470668"),
ChoferModel(firstName: "EDGAR", lastName: "MOLINA CHAVES", choferNationalId: "604170126"),
ChoferModel(firstName: "JOSEPH", lastName: "OVIEDO SALAZAR", choferNationalId: "115380121"),
ChoferModel(firstName: "SERGIO", lastName: "ROJAS ALFARO", choferNationalId: "2669505"),
ChoferModel(firstName: "ALEJANDRO", lastName: "RODRIGUEZ CALDERON", choferNationalId: "304300592"),
ChoferModel(firstName: "ERICK", lastName: "ABARCA PICADO", choferNationalId: "113120132"),
ChoferModel(firstName: "OSCAR A", lastName: "CONEJO FALLAS", choferNationalId: "11007612"),
ChoferModel(firstName: "JUAN", lastName: "PICADO MONTERO", choferNationalId: "11167742"),
ChoferModel(firstName: "ANDREY", lastName: "GUERRERO CORTES", choferNationalId: "6425847"),
ChoferModel(firstName: "MICHAEL", lastName: "ALVARADO BRENES", choferNationalId: "702050015"),
ChoferModel(firstName: "JUAN MIGUEL", lastName: "SALAZAR ROJAS", choferNationalId: "113170210"),
ChoferModel(firstName: "OSCAR", lastName: "SAENZ CHAVES", choferNationalId: "2413438"),
ChoferModel(firstName: "MAURICIO", lastName: "AVILA MENDOZA", choferNationalId: "110870312"),
ChoferModel(firstName: "ESTEBAN", lastName: "ARTAVIA VEGA", choferNationalId: "7217856"),
ChoferModel(firstName: "JAVIER", lastName: "CARRANZA AVILA", choferNationalId: "603780045"),
ChoferModel(firstName: "CARLOS", lastName: "MARTINEZ MARIN", choferNationalId: "1752850"),
ChoferModel(firstName: "MANFRED", lastName: "PERAZA ROJAS", choferNationalId: "111050868"),
ChoferModel(firstName: "KEVIN ANDRES", lastName: "ARAYA SOLORZANO", choferNationalId: "117260748"),
ChoferModel(firstName: "EMANUEL", lastName: "ARIAS MORALES", choferNationalId: "207940457"),
ChoferModel(firstName: "JUAN DIEGO", lastName: "ALVAREZ ROJAS", choferNationalId: "2635816"),
ChoferModel(firstName: "JUAN JOSE", lastName: "SOLIS SOLIS", choferNationalId: "107790381"),
ChoferModel(firstName: "JONAIKER", lastName: "MORA CRUZ", choferNationalId: "7275180"),
ChoferModel(firstName: "MARIO", lastName: "LORIA ARAYA", choferNationalId: "6201136"),
ChoferModel(firstName: "JORGE", lastName: "QUESADA ROJAS", choferNationalId: "110270805"),
ChoferModel(firstName: "FERNANDO", lastName: "QUESADA VILLALOBOS", choferNationalId: "2484760"),
ChoferModel(firstName: "ALEXANDER", lastName: "VARGAS BARTH", choferNationalId: "2665173"),
ChoferModel(firstName: "CARLOS", lastName: "ESQUIVEL CARAZO", choferNationalId: "2640971"),
ChoferModel(firstName: "CRISTHOFER", lastName: "QUESADA SALAZAR", choferNationalId: "2080000157"),
ChoferModel(firstName: "CRISTIAN", lastName: "SANDI ALVARADO", choferNationalId: "2564151"),
ChoferModel(firstName: "DIEGO", lastName: "GUADAMUZ HERNANDES", choferNationalId: "6381933"),
ChoferModel(firstName: "MAICOL", lastName: "CORRALES FAJARDO", choferNationalId: "6393155"),
ChoferModel(firstName: "DIXON ANTONIO", lastName: "VILLGAS SEGURA", choferNationalId: "5388806"),
ChoferModel(firstName: "CARLOS SIVIANY", lastName: "JIMENEZ MIRANDA", choferNationalId: "2639685"),
ChoferModel(firstName: "DAGO ANDRES", lastName: "BERMUDEZ QUESA", choferNationalId: "2694337"),
ChoferModel(firstName: "BRAINER", lastName: "MORA CHAVEZ", choferNationalId: "5248112"),
];




